### ISSUE TITLE
Bug: Token type IDs not created for RoBERTa

### ISSUE THREAD

**Issue by TLecailtel** [wtma/CharBERT#4]
Hello, thanks a lot for this repo.

### Problem

When running the GLUE benchmark with a RoBERTa model, I get a `KeyError: 'token_type_ids'`.

### Cause

The RoBERTa model doesn't need token type IDs (as explained [here](https://huggingface.co/transformers/model_doc/roberta.html#overview)), so its Hugging Face tokenizer doesn't automatically create them.
But your code from `processors/glue.py` expects token type IDs to exist, no matter which model type is used.

### Solution

A working solution for me was to add the `return_token_type_ids=True` param to the `tokenizer.encode_plus` method call (just after [this line](https://github.com/wtma/CharBERT/blob/6b9bf71fada92468c7596b9a6fc173a274cc5b58/processors/glue.py#L96)).
So the tokenizer will create dummy token type IDs (as explained [here](https://huggingface.co/transformers/model_doc/roberta.html#transformers.RobertaTokenizer.create_token_type_ids_from_sequences)), that won't be used but will exist anyway, hence solving the bug.

What do you think?

**Comment by mawentao277** [comment]
Hello, I think it's probably because we run the code with different versions of transformers.
I have wrote the codes with the version 2.4.0 and the default value for `return_token_type_ids ` is True, just in [this line](https://github.com/huggingface/transformers/blob/6664ea943d75e7ab2cc78e7d97bdf38d7a00acb4/src/transformers/tokenization_utils.py#L1543)

**Comment by mawentao277** [comment]
You can reopen the issue is you need
